import { MigrationInterface, QueryRunner } from "typeorm";

export class AddRegistrationToken1779678258535 implements MigrationInterface {
    name = 'AddRegistrationToken1779678258535'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "person_achievement" ("id" BIGSERIAL NOT NULL, "person_id" bigint NOT NULL, "achievement_name" text NOT NULL, "obtained_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7dbce3540a237b3781b4b9fe583" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_db63ef18d70805c5d8cf35ed60" ON "person_achievement" ("person_id") `);
        await queryRunner.query(`ALTER TABLE "camp" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "camp" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "temporary_assignment" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "temporary_assignment" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "profession" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "profession" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ai_admission" ADD "registration_token" text`);
        await queryRunner.query(`ALTER TABLE "ai_admission" ADD "token_expires_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "ai_admission" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ai_admission" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "person" ADD "experience_points" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "person" ADD "expeditions_survived" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "person" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "person" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "role" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "role" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "session" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "session" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_account" ADD "status" text NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "user_account" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_account" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_asset" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_asset" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "request_person_detail" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "request_person_detail" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approval" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approval" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ADD "travel_days" integer`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ADD "departure_date" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ADD "arrival_date" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory_movement" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory_movement" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "resource" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "resource" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "request_resource_detail" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "request_resource_detail" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "daily_production" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "daily_production" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "daily_consumption" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "daily_consumption" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "exploration_person" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "exploration_person" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "exploration_resource" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "exploration_resource" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "exploration" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "exploration" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "login_attempt" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "login_attempt" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ai_admission" DROP COLUMN "candidate_data"`);
        await queryRunner.query(`ALTER TABLE "ai_admission" ADD "candidate_data" jsonb NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ai_admission" DROP COLUMN "raw_ai_response"`);
        await queryRunner.query(`ALTER TABLE "ai_admission" ADD "raw_ai_response" jsonb`);
        await queryRunner.query(`ALTER TABLE "person" DROP COLUMN "ai_admission_result"`);
        await queryRunner.query(`ALTER TABLE "person" ADD "ai_admission_result" jsonb`);
        await queryRunner.query(`ALTER TABLE "asset" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "asset" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "user_asset" ALTER COLUMN "acquired_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_asset" ALTER COLUMN "acquired_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "user_asset" DROP COLUMN "context_data"`);
        await queryRunner.query(`ALTER TABLE "user_asset" ADD "context_data" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "old_value"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "old_value" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "new_value"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "new_value" jsonb`);
        await queryRunner.query(`ALTER TABLE "login_attempt" ALTER COLUMN "username" SET NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_f39fc89bd5bd3e91f17e97ca13" ON "temporary_assignment" ("user_account_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9f9c60236fefb096dd9986c033" ON "temporary_assignment" ("profession_origin_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_939d2a5516cd7514778875981f" ON "temporary_assignment" ("profession_temporary_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1eccb81f76a02d31df0536c70a" ON "temporary_assignment" ("user_approve_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a179b44696a162008be9db952f" ON "ai_admission" ("camp_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ae034d683450cfe2fea8001882" ON "ai_admission" ("person_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_063df483418602c2fb6401e30c" ON "ai_admission" ("suggested_profession_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b348055bc1beab35e76f56064f" ON "ai_admission" ("reviewed_by_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6138d5adc14a4fec23ffbdff1b" ON "person" ("profession_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_30e98e8746699fb9af235410af" ON "session" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_96b8004eec0c40ce3b5a82818f" ON "user_account" ("camp_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c57754862d92d288007ce87b4a" ON "user_account" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_99363caa241d8d2c2c6426f682" ON "user_asset" ("user_account_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cec0df5ab1298779a72f797d5a" ON "user_asset" ("asset_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b0c8dca5603814119d413f7f69" ON "request_person_detail" ("request_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_65d17b6e9cf9177ab5f4095d1f" ON "request_person_detail" ("person_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d677c4995c462988eb7234992a" ON "approval" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_957000ac5492d83bf03e067a36" ON "approval" ("entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_40db11664c60dfa912e804f426" ON "intercamp_request" ("camp_origin_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bfc6c67564d10dd50383218e23" ON "intercamp_request" ("camp_destination_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_eaed702aa88f18f6f12d08b663" ON "inventory" ("camp_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6297526d69f7534eb30a98a2ea" ON "inventory" ("resource_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_caa8296286b897e16e9e73a52d" ON "inventory_movement" ("resource_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_681fa4cca6407411785c39b0c7" ON "inventory_movement" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2ed19f951bd4d63d42a5e94e26" ON "inventory_movement" ("camp_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ccd02cf385845aa20213a32391" ON "request_resource_detail" ("request_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_756f80c9464879be5cb2a596ec" ON "request_resource_detail" ("resource_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_677fdc297f3cbf60f249ac5831" ON "daily_production" ("camp_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f5f75a336846bf56ab940bc6ee" ON "daily_production" ("profession_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5746f0607a4b24feb870d82ff3" ON "daily_production" ("resource_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e75e9e8ab3662332340a8bb20f" ON "daily_consumption" ("camp_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_84b7767a833adde4bb67c1515d" ON "daily_consumption" ("person_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a5b9735af7febaa9906d8302bd" ON "daily_consumption" ("resource_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f0da4f862c75807754ddade2f5" ON "exploration_person" ("exploration_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3a8c01bedddc7acc47c18e6cf7" ON "exploration_person" ("person_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4e8efa7cd74288573974c9eced" ON "exploration_resource" ("exploration_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_eea4bf151b6705e9ed6276d4a3" ON "exploration_resource" ("resource_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_774908429dc92bbf289590bee6" ON "exploration" ("camp_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b1b765d415240b3f50ede6eac" ON "exploration" ("user_create_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cb11bd5b662431ea0ac455a27d" ON "audit_log" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5962a15097be3de126a10e08ab" ON "audit_log" ("camp_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_701cda80ec8ef990a31c06b296" ON "login_attempt" ("ip_address") `);
        await queryRunner.query(`CREATE INDEX "IDX_53c132af0365241b076e32b50e" ON "login_attempt" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "person_achievement" ADD CONSTRAINT "FK_db63ef18d70805c5d8cf35ed606" FOREIGN KEY ("person_id") REFERENCES "person"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "login_attempt" ADD CONSTRAINT "FK_53c132af0365241b076e32b50ee" FOREIGN KEY ("user_id") REFERENCES "user_account"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "login_attempt" DROP CONSTRAINT "FK_53c132af0365241b076e32b50ee"`);
        await queryRunner.query(`ALTER TABLE "person_achievement" DROP CONSTRAINT "FK_db63ef18d70805c5d8cf35ed606"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_53c132af0365241b076e32b50e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_701cda80ec8ef990a31c06b296"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5962a15097be3de126a10e08ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb11bd5b662431ea0ac455a27d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b1b765d415240b3f50ede6eac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_774908429dc92bbf289590bee6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eea4bf151b6705e9ed6276d4a3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e8efa7cd74288573974c9eced"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3a8c01bedddc7acc47c18e6cf7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0da4f862c75807754ddade2f5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a5b9735af7febaa9906d8302bd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_84b7767a833adde4bb67c1515d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e75e9e8ab3662332340a8bb20f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5746f0607a4b24feb870d82ff3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f5f75a336846bf56ab940bc6ee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_677fdc297f3cbf60f249ac5831"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_756f80c9464879be5cb2a596ec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccd02cf385845aa20213a32391"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ed19f951bd4d63d42a5e94e26"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_681fa4cca6407411785c39b0c7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_caa8296286b897e16e9e73a52d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6297526d69f7534eb30a98a2ea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eaed702aa88f18f6f12d08b663"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bfc6c67564d10dd50383218e23"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40db11664c60dfa912e804f426"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_957000ac5492d83bf03e067a36"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d677c4995c462988eb7234992a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65d17b6e9cf9177ab5f4095d1f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b0c8dca5603814119d413f7f69"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cec0df5ab1298779a72f797d5a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99363caa241d8d2c2c6426f682"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c57754862d92d288007ce87b4a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_96b8004eec0c40ce3b5a82818f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30e98e8746699fb9af235410af"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6138d5adc14a4fec23ffbdff1b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b348055bc1beab35e76f56064f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_063df483418602c2fb6401e30c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae034d683450cfe2fea8001882"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a179b44696a162008be9db952f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1eccb81f76a02d31df0536c70a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_939d2a5516cd7514778875981f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f9c60236fefb096dd9986c033"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f39fc89bd5bd3e91f17e97ca13"`);
        await queryRunner.query(`ALTER TABLE "login_attempt" ALTER COLUMN "username" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "new_value"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "new_value" json`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "old_value"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "old_value" json`);
        await queryRunner.query(`ALTER TABLE "user_asset" DROP COLUMN "context_data"`);
        await queryRunner.query(`ALTER TABLE "user_asset" ADD "context_data" json`);
        await queryRunner.query(`ALTER TABLE "user_asset" ALTER COLUMN "acquired_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_asset" ALTER COLUMN "acquired_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "asset" ADD "metadata" json`);
        await queryRunner.query(`ALTER TABLE "person" DROP COLUMN "ai_admission_result"`);
        await queryRunner.query(`ALTER TABLE "person" ADD "ai_admission_result" json`);
        await queryRunner.query(`ALTER TABLE "ai_admission" DROP COLUMN "raw_ai_response"`);
        await queryRunner.query(`ALTER TABLE "ai_admission" ADD "raw_ai_response" json`);
        await queryRunner.query(`ALTER TABLE "ai_admission" DROP COLUMN "candidate_data"`);
        await queryRunner.query(`ALTER TABLE "ai_admission" ADD "candidate_data" json NOT NULL`);
        await queryRunner.query(`ALTER TABLE "login_attempt" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "login_attempt" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "exploration" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "exploration" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "exploration_resource" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "exploration_resource" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "exploration_person" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "exploration_person" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "daily_consumption" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "daily_consumption" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "daily_production" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "daily_production" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "request_resource_detail" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "request_resource_detail" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "resource" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "resource" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_movement" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_movement" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" DROP COLUMN "arrival_date"`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" DROP COLUMN "departure_date"`);
        await queryRunner.query(`ALTER TABLE "intercamp_request" DROP COLUMN "travel_days"`);
        await queryRunner.query(`ALTER TABLE "approval" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "approval" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "request_person_detail" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "request_person_detail" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user_asset" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user_asset" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user_account" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user_account" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user_account" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "session" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "session" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "person" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "person" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "person" DROP COLUMN "expeditions_survived"`);
        await queryRunner.query(`ALTER TABLE "person" DROP COLUMN "experience_points"`);
        await queryRunner.query(`ALTER TABLE "ai_admission" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "ai_admission" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "ai_admission" DROP COLUMN "token_expires_at"`);
        await queryRunner.query(`ALTER TABLE "ai_admission" DROP COLUMN "registration_token"`);
        await queryRunner.query(`ALTER TABLE "profession" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "profession" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "temporary_assignment" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "temporary_assignment" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "camp" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "camp" DROP COLUMN "created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db63ef18d70805c5d8cf35ed60"`);
        await queryRunner.query(`DROP TABLE "person_achievement"`);
    }

}
